### ISSUE TITLE
Provide more static guarantees for keys

### ISSUE THREAD

**Issue by ilammy** [ilammy/rust-themis#4]
Currently Themis uses opaque byte buffers to represent keys. Functions that generate keys return `Vec<u8>`, functions that consume keys accept `&[u8]`. It's very convenient and easy to work with.

However, there are a number of expectations these functions place on the keys:

* Secure Message in sign/verify mode expects only secret or public keys
* Secure Message in encryption mode expects matching pairs of keys
* Secure Session supports only ECDSA keys
* all of them expect that buffers contain valid keys generated by Themis

Of course, these requirements are verified at run-time, but it delays error discovery for quite some time. It's quite disappointing to see your server successfully start up, read in all the peer keys from files, and then fail after several hours when that particular peer connects via Secure Session, that one whose public key file contains invalid data, but you only learn about that now when Themis actually tries using the key.

It would be nice to provide more strong guarantees about key validity. We could distinguish between key types and kinds statically. If `EcdsaSecretKey` and `RsaPublicKey` are a thing then it is impossible to misplace them in your code. If Secret Message works only with `KeyPair` that enforces matching key types then it is impossible to accidentally pair up RSA secret key with ECDSA's public one. If all key type constructors return `Result` then you have to deal with parsing errors right now, not later.

- [x] Introduce strong key types
- [x] Update existing code to them
- [x] Provide tests and examples
- [x] Consider usability and readablity
- [x] Consider additional security

**Comment by vixentael** [comment]
Agree, have the same feelings about iOS wrapper as well. Some languages support strong types, and we should definitely use this.

**Comment by ilammy** [comment]
Now, a bit on security.

All key material is now stored in `KeyBytes` structures (which simply wrap byte vectors). This should make is easier to review the code that deals with keys as they are now clearly marked as something imporant.

It is also now possible to implement a good security practice of zeroing out memory when keys are destroyed. This should prevent accidental leaks of key material. (However, I'm too lazy for that right now. And I'm not sure if that will actually do any practical good, especially without auditing Themis Core and implementing zeroing there as well.)

Another thing that I would like to mention is _pointer alignment_. While I was working on key validation I have been given a warning by Rust (and then C) compiler about unsafe casts of pointers passed to `soter_verify_container_checksum()`. Indeed, most of Themis functions accept `void*` pointers (which have 1-byte natural alignment) and then merrily cast them into `soter_container_hdr_t*` pointers (which have 4-byte natural alignment). This is technically undefined behavior and may cause the compiler to generate code that may crash on some machines. (Read more free technical rants [in the source code][4].)

[4]: https://github.com/ilammy/rust-themis/blob/b8e9bb6c3a8526a9683bde5d9ba046b0e56539ba/libthemis-sys/src/wrapper.c#L27-L50

Admittedly, it is highly unlikely to encounter catastrophic consequences of such casts (mostly because modern hardware had given up any hopes in human ability to write safe C code without undefined behavior). Indeed, I was unable to trigger incorrect behavior on my reasonably modern Android phone with ARM CPU. Non-handheld computers nowadays mostly use x86_64 CPUs which are not affected by this particular issue. And various embedded devices are unlikely to use Themis for their cryptography. However, theoretical issue with unaligned memory access still exists.

Using `KeyBytes` prevents alignment issues. But keys are not the only ones affected, all other byte slices that are eventually passed to `soter_verify_container_checksum()` may trigger undefined behavior. I did not overextend myself with fixing that because I do not have any example that makes Themis crash on some device. But FIXME still exists in the source code, maybe we'll do something about it someday.
